# Generated by Django 5.2.17 on 2026-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, help_text="Pilgrim's departure city", max_length=100)),
                ('tour_interest', models.CharField(help_text='Tour or circuit interested in', max_length=200)),
                ('number_of_pilgrims', models.PositiveIntegerField(default=1)),
                ('preferred_travel_date', models.CharField(blank=True, help_text='e.g. May 2026 or specific date', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted / In Progress'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Cancelled / Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by Swarnav team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Inquiry',
                'verbose_name_plural': 'Booking Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilgrim_name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, help_text='e.g. Surat, Ahmedabad, Mumbai', max_length=100)),
                ('yatra_name', models.CharField(help_text='e.g. Char Dham Yatra', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars')),
                ('review_text', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. North India Tours', max_length=150)),
                ('slug', models.SlugField(help_text='e.g. north-india', max_length=150, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Himalayan Holy Shrines & Mountain Valleys', max_length=255)),
                ('badge', models.CharField(blank=True, help_text='e.g. Sacred Garhwal & Kashmir', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(default='🛡️', help_text='Emoji or icon name (e.g. 🚆, 🛡️, 🍲)', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Feature',
                'verbose_name_plural': 'Why Choose Us Features',
                'ordering': ['order'],
            },
        ),
    ]
