# Generated by Django 5.2.17 on 2026-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(choices=[('char-dham', 'Char Dham Yatra (13 Days – ₹30,000)'), ('panch-kedar', 'Panch Kedar Yatra (10 Days – ₹26,500)'), ('kashmir-paradise', 'Kashmir Tour (7 Days – ₹22,500)'), ('rameshwaram-circuit', 'Rameshwaram & South Circuit (8 Days – ₹24,000)'), ('kerala-tour', 'Kerala Tour (6 Days – ₹19,500)'), ('jagannath-puri', 'Jagannath Puri Odisha (11 Days – ₹24,500)'), ('jharkhand-tour', 'Jharkhand Spiritual Yatra (5 Days – ₹14,500)'), ('nepal-pashupatinath-muktinath', 'Nepal Pashupatinath Muktinath (8 Days – ₹34,500)'), ('general', 'General Pilgrimage Inquiry')], default='char-dham', max_length=50, verbose_name='Selected Tour')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone / WhatsApp Number')),
                ('departure_city', models.CharField(blank=True, help_text="Pilgrim's departure or home city (optional)", max_length=100, verbose_name='Departure City')),
                ('total_pilgrims', models.PositiveIntegerField(blank=True, help_text='Number of pilgrims travelling (optional)', null=True, verbose_name='Total Pilgrims')),
                ('message', models.TextField(blank=True, help_text='Preferred travel month, train/flight requests or special requirements (optional)', verbose_name='Message / Preferred Month')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Inquiry Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Private internal notes visible only to administrators', verbose_name='Private Admin Notes')),
                ('consent_given', models.BooleanField(default=False, help_text='Whether the customer agreed to be contacted regarding this inquiry', verbose_name='Consent Given')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BookingInquiry',
        ),
    ]
