# Generated by Django 5.2.17 on 2026-09-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. char-dham, jagannath-puri', max_length=150, unique=True)),
                ('name', models.CharField(help_text='e.g. Char Dham Yatra', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Yamunotri • Gangotri • Kedarnath • Badrinath', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, help_text='e.g. North India (Uttarakhand)', max_length=150)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('duration_nights', models.PositiveIntegerField(default=0)),
                ('duration_display', models.CharField(blank=True, help_text='e.g. 13 Days / 12 Nights', max_length=100)),
                ('starting_price', models.CharField(blank=True, help_text='e.g. ₹30,000', max_length=50)),
                ('price_display', models.CharField(blank=True, help_text='e.g. Starting from ₹30,000 per person', max_length=150)),
                ('price_note', models.CharField(blank=True, help_text='e.g. per person (Triple-sharing)', max_length=150)),
                ('starting_city', models.CharField(default='Surat, Gujarat', max_length=150)),
                ('ending_city', models.CharField(default='Surat, Gujarat', max_length=150)),
                ('origin', models.CharField(blank=True, help_text='e.g. Starts & Ends in Surat, Gujarat', max_length=200)),
                ('home_city_connect', models.CharField(default='Train or flight from your home city can be arranged', help_text='Connectivity note for pilgrims from other cities', max_length=255)),
                ('departures_summary', models.CharField(blank=True, max_length=255)),
                ('departures_guidance', models.TextField(blank=True)),
                ('accommodation_summary', models.TextField(blank=True)),
                ('meals_summary', models.TextField(blank=True)),
                ('transport_summary', models.TextField(blank=True)),
                ('confirmation_note', models.TextField(blank=True)),
                ('gujarat_support_note', models.TextField(blank=True)),
                ('brief_guide', models.TextField(blank=True)),
                ('introduction', models.JSONField(blank=True, default=list, help_text='List of paragraphs')),
                ('route_highlights', models.JSONField(blank=True, default=list, help_text='List of key stops/cities')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Key highlights bullet points')),
                ('image', models.CharField(default='images/kedarnath-temple.jpg', help_text='Static image path or asset URL', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active / Complete Guide Available'), ('upcoming', 'Upcoming / Inquiries Open'), ('seasonal', 'Seasonal Bookings Open'), ('draft', 'Draft / Hidden')], default='upcoming', max_length=20)),
                ('status_label', models.CharField(blank=True, help_text='e.g. Complete Guide Available', max_length=100)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether full multi-page portal is available')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering within its category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Circuit category (e.g. North India, South India)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='core.tourcategory')),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StayAndTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_options', models.JSONField(blank=True, default=list)),
                ('vehicle_guidelines', models.JSONField(blank=True, default=list)),
                ('baggage_rules', models.JSONField(blank=True, default=list)),
                ('meal_guidelines', models.JSONField(blank=True, default=list)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stay_and_travel', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Stay & Travel Configuration',
                'verbose_name_plural': 'Stay & Travel Configurations',
            },
        ),
        migrations.CreateModel(
            name='PolicyAndFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_policy', models.JSONField(blank=True, default=list)),
                ('payment_terms', models.JSONField(blank=True, default=list)),
                ('general_terms', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Policies & FAQs',
                'verbose_name_plural': 'Policies & FAQs',
            },
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('pricing_structure', models.JSONField(blank=True, default=list)),
                ('booking_guidelines', models.JSONField(blank=True, default=list)),
                ('key_highlights', models.JSONField(blank=True, default=list)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_detail', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Package Details & Inclusions',
                'verbose_name_plural': 'Package Details & Inclusions',
            },
        ),
        migrations.CreateModel(
            name='DhamDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('significance', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('highlight', models.CharField(blank=True, max_length=150)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhams', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Dham / Key Destination',
                'verbose_name_plural': 'Dhams / Key Destinations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.JSONField(blank=True, default=list)),
                ('packing_list', models.JSONField(blank=True, default=list)),
                ('registration_process', models.JSONField(blank=True, default=list)),
                ('medical_advisory', models.JSONField(blank=True, default=list)),
                ('local_customs', models.JSONField(blank=True, default=list)),
                ('senior_citizen_tips', models.JSONField(blank=True, default=list)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_guide', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Travel Guide & Preparation',
                'verbose_name_plural': 'Travel Guides & Preparation',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3...')),
                ('title', models.CharField(help_text='e.g. Surat to Haridwar', max_length=255)),
                ('starting_point', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('intro', models.TextField(blank=True)),
                ('route_summary', models.CharField(blank=True, help_text='e.g. Surat ➔ Haridwar', max_length=255)),
                ('night_stay', models.CharField(blank=True, help_text='e.g. Haridwar, Barkot', max_length=150)),
                ('hotel_type', models.CharField(blank=True, default='Economy Hotel', max_length=100)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('meals', models.CharField(blank=True, help_text='e.g. Lunch & Dinner', max_length=150)),
                ('altitude', models.CharField(blank=True, help_text='e.g. 3,583 m (11,755 ft)', max_length=100)),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Dict with morning, afternoon, evening, notes')),
                ('darshan_tips', models.JSONField(blank=True, default=list, help_text='List of darshan tips')),
                ('scenic_points', models.JSONField(blank=True, default=list, help_text='List of scenic points')),
                ('places_covered', models.JSONField(blank=True, default=list, help_text='List of place objects with images and descriptions')),
                ('route_nodes', models.JSONField(blank=True, default=list, help_text='List of route node objects for visual timeline')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='yatras.tourpackage')),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Days',
                'ordering': ['tour', 'day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
    ]
