# Generated by Django 5.2.17 on 2026-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='altitude',
            field=models.CharField(blank=True, default='', help_text='e.g. 3,583 m (11,755 ft)', max_length=100),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='hotel_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='meals',
            field=models.CharField(blank=True, default='', help_text='e.g. Lunch & Dinner', max_length=150),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='night_stay',
            field=models.CharField(blank=True, default='', help_text='e.g. Haridwar, Barkot', max_length=150),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='route_summary',
            field=models.CharField(blank=True, default='', help_text='e.g. Surat ➔ Haridwar', max_length=255),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='starting_point',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
